# Configuration for travis

language: r

python:
  - "3.6"

sudo: required

warnings_are_errors: true

r-packages:
  - reticulate
  - rmarkdown
  - Rcpp

r_check_args: --no-vignettes --no-build-vignettes

r_github_packages:
  - r-lib/covr

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install numpy scipy scikit-learn numba umap-learn

after_success:
  - Rscript -e 'covr::codecov()'
